trigger:
- master

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'


pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
